// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

var TableNames = struct {
	SchemaMigrations string
	Users            string
}{
	SchemaMigrations: "schema_migrations",
	Users:            "users",
}
