version: "3"
services:
    go:
        build: ./go
        tty: true
        depends_on:
            - db
        ports:
            - "8080:8080"
        volumes:
            - ./app:/go/src/app
    db:
        build: ./mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: pw
        command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
        ports:
            - 3306:3306
        volumes:
            - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnfl
# volumes:
#   mysql-db:
