version: "3"
services:
    go:
        build: ./docker/go
        tty: true
        depends_on:
            - db
        ports:
            - "8080:8080"
        volumes:
            - ./app:/go/src/app
    node:
        build: ./docker/node
        # ないと落ちるので設定
        tty: true
        depends_on:
            - db
            - go
        volumes:
            - ./frontend:/frontend
        ports:
            - "4000:3000"
    db:
        build: ./docker/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: pw
        command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
        ports:
            - 3306:3306
        volumes:
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnfl
# volumes:
#   mysql-db:
